# Generated by Django 2.2.6 on 2019-10-28 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='likes',
            field=models.ManyToManyField(related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movies',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='movie_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
