# Generated by Django 2.2.6 on 2019-10-28 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20191028_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='likes',
        ),
        migrations.AddField(
            model_name='movies',
            name='like_users',
            field=models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
